DROP TABLE IF EXISTS options CASCADE;

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  number INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  is_solution BOOLEAN NOT NULL DEFAULT FALSE
);